### ISSUE TITLE
Crashing with update 101

### ISSUE THREAD

**Issue by cschermerhorn** [polarathene/biglobby#13]
Seems this is no longer working with update 101.

Can solo load with bots.  Game instantly crashing once 1 or more people attempting joining.  Crash only occurring once map begins to load with multiple players, or once an additional player joins a heist in progress.

**Comment by polarathene** [comment]
Please share a crashlog.txt via pastebin or other service. It's incredibly difficult for me to debug on linux as these are not available. I will try fix it with whatever information I can be given, but finding players to test when I'm available is usually difficult.

**Comment by cschermerhorn** [comment]
I've placed the log here, I believe this is what you were looking for.  Let me know if this doesn't work as a hosting environment.  ~~2016_06_12_log.txt~~

**Comment by polarathene** [comment]
@cschermerhorn That is your BLT log file. Not the crashlog I'm interested in, see this: https://steamcommunity.com/app/218620/discussions/14/530645446323387705/

**Comment by cschermerhorn** [comment]
@polarathene Apologies.  This should be the correct one based on the link you posted:  
[crashlog.txt](https://github.com/polarathene/biglobby/files/311113/crashlog.txt)

**Comment by polarathene** [comment]
Crash is due to this line/call: https://github.com/polarathene/biglobby/blob/master/biglobby/lua/lib/network/base/_networkpeer.lua#L16

I'll probably need to find some time to dig in further with log debugging and test with others. Seems to be due to the function call `update_grenades_amount_to_peers()` called from player manager's `_set_grenade()` when spawning a player.

I think this was a recent change in network code for U100, U101 may have changed it or I may have not supported it properly.

**Comment by polarathene** [comment]
`network.network_settings` likely network call is [`sync_grenades`](https://github.com/polarathene/biglobby/commit/24ef820201a7131fc0994e1e974ee8539f277249?diff=unified#diff-a823b9734566cd2fd1ced4c85b72d4e9L1204), `biglobby__` prefix [here](https://github.com/polarathene/biglobby/commit/24ef820201a7131fc0994e1e974ee8539f277249?diff=unified#diff-a823b9734566cd2fd1ced4c85b72d4e9R2015)

Bug appears to be a typo, the `biglobby__` prefix is only using one underscore instead of two. This applies to both unit and function names. Correcting the xml file and recreating the pdmod should fix this. The typo is present in the other network functions added for U100 commit, these need to be corrected too.

@cschermerhorn thank you for the report and helpful crashlog. I'll fix this later tonight when I'm home.

**Comment by polarathene** [comment]
@cschermerhorn [This](https://github.com/polarathene/biglobby/releases/tag/v2.0.0-alpha) should hopefully be crashfree, try the new 2.0.2 zip download link :)

**Comment by cschermerhorn** [comment]
@polarathene I'll report back when I can.  Glad to see it's fixed!
