### ISSUE TITLE
Crash on sentry placement

### ISSUE THREAD

**Issue by YellowMacho** [polarathene/biglobby#14]
Playing a heist on Train Heist on overkill when one of the clients placed a sentry, which crashed all clients but not the host.  There was 1 host and 3 clients and 2 bots. I've provided the crash log.

My buddies and I are really interested in your mod and are a group of 6 trying to find the kinks, we're probably going to overwhelm ya with the reports :/
[payday26-14-16.txt](https://github.com/polarathene/biglobby/files/315359/payday26-14-16.txt)

**Comment by polarathene** [comment]
```
PAYDAY 2 Crash log
Application has crashed: C++ exception
[string "lib/network/base/handlers/basenetworkhandle..."]:125: attempt to index local 'rpc' (a nil value)
```

This is supposedly what crashed you. It's pointing to games code, not my own override. That said if everyone has the pdmod and blt mod enabled properly, then it could still be I'm not handling a network call properly.
- Are you able to reproduce and verify sentry placement causes the crash?
- Does this happen only on Train Heist/overkill or on any level/difficulty when placing a sentry?
- Any other mods like Hoxhud enabled? (It's possible Host or Client with other mods may conflict)

I see you have WolfHUD enabled and throwing this error:
`Failed parsing mods.txt of WolfHUD, Message: After parsing a value an unexpected character was encountered: ". Path 'hooks[50].hook_id', line 59, position 59.`
No idea if that is causing any problems.

It's possibly due to the new sentry changes introduced with U100+, if you can confirm that other levels/difficulty can trigger the crash on sentry placement, I'll take a look at that. If it's specific to the level/difficulty that would also help narrow where to look.

Bug reports welcome :) I don't have time to test myself and would love to have the mod in good condition!

**Comment by YellowMacho** [comment]
Update, reproduced the crash with several different people and PCs.
- Map is not related, tested on train heist, jewelry heist, and slaughterhouse.
- Everyone including host is using completely vanilla games.
Again, only crashes the clients when a sentry is placed.
NOTE: Clients can join a game that already has sentries on the map; HOWEVER, if anyone, including host, places a sentry, then all clients crash.  It seems the bug is related to the placing of sentries rather than them actually being rendered on the map.

Any more questions or scenarios just let me know.

**Comment by YellowMacho** [comment]
Update here:
- Crash does not seem to be related to map, tested on jewelry store, slaughterhouse, train heist.
- Crash not related to difficulty, tested on normal, overkill, deathwish.
- Completely vanilla games for all players including host besides big lobby mod.

What was interesting is the crash does not seem to actually be related to the sentry being rendered, as a client can join a game with sentries already on the map.  If either a host or any client places a sentry, all clients crash.  Host never crashes.  Both suppressed and unsupressed sentries cause crash.

Here are 3 of the many crash logs, all named on scenario:

[jewelry store normal difficulty host place sentry crash.txt](https://github.com/polarathene/biglobby/files/317260/jewelry.store.normal.difficulty.host.place.sentry.crash.txt)
[slaughterhouse deathwish difficulty host place sentry crash.txt](https://github.com/polarathene/biglobby/files/317261/slaughterhouse.deathwish.difficulty.host.place.sentry.crash.txt)
[slaughterhouse deathwish difficulty client place sentry crash.txt](https://github.com/polarathene/biglobby/files/317262/slaughterhouse.deathwish.difficulty.client.place.sentry.crash.txt)

We've also found another unrelated bug we'll thoroughly test tomorrow and submit.

**Comment by polarathene** [comment]
Bug is due to updated network function signature for [`from_server_sentry_gun_place_result`](https://github.com/polarathene/biglobby/commit/24ef820201a7131fc0994e1e974ee8539f277249#diff-a823b9734566cd2fd1ced4c85b72d4e9L990).

Althoough I added it for regular lobby support I forgot to add the new parameter for damage multiplier: `<param type="int" min="0" max="8" />   <!-- damage multiplier -->`

You can add this to the `biglobby__` prefixed version and recreate the pdmod to fix this. I'll update the codebase and make a bugfix release when I get home from work(about 9 hours from now).

Thankyou for the informative bug report and help with testing :) Bring on the bugs!

**Comment by polarathene** [comment]
@YellowMacho please try out the bugfix in ~~2.0.4 release [here](https://github.com/polarathene/biglobby/releases/tag/v2.0.0-alpha)~~ [`2.0.5--alpha`](https://github.com/polarathene/biglobby/releases/download/v2.0.0-alpha/biglobby-2.0.5-alpha.zip). Let me know if that fixes it :)

**Comment by polarathene** [comment]
Closing, no response.
