### ISSUE TITLE
crash on join

### ISSUE THREAD

**Issue by this310** [polarathene/biglobby#15]
since the biker patch it worked yesterday the game crashes as soon as someone joins

**Comment by polarathene** [comment]
If a new patch is out since U101, there might be new network functions, or existing ones might have changed their function signature/params.

There was a bug fixed in 2.0.3-alpha where placing sentries would crash players other than the host.
- Can you confirm that you were the host and a player joining your game crashed you and not just them? Or were you joining a biglobby game and crashing?
- What version of BigLobby are you using?(best reliable way to tell right now is the filename of the .zip file you downloaded from releases page).
- Please submit a crashlog(you can use a web service like pastebin). This will help me identify where the crash is coming from.

**Comment by polarathene** [comment]
@this310 Please try latest version v2.0.4-alpha. You can find it [here on the release page](https://github.com/polarathene/biglobby/releases/tag/v2.0.0-alpha), if you still crash please answer questions.

**Comment by this310** [comment]
ok ill try to get the new version ill reply if it has any issues

**Comment by ShieldOfHolyShadows** [comment]
I had the same problem because I didn't know I needed to do stuff with the Bundle Modder after the game updated.  I fixed it by verifying the game cache, then re-adding the PDMOD file with bundle modder.

**Comment by polarathene** [comment]
@ShieldOfHolyShadows yes, that should be added to instructions. When game updates, you will probably have to verify cache if you have not disabled pdmod, this might only need to happen if game updates the bundle file pdmod patches. Then you apply pdmod again(or new version on releases in case update breaks the mod again, happens often).

Let me know if if the latest release fixes crash :) You should only see players on crime.net with latest version when using it, not players with older mod version. BLT updater is not able to update BigLobby yet, you must do manually until this mod is released on Last Bullet and gets official update support.

**Comment by polarathene** [comment]
Closing, no response.
