### ISSUE TITLE
Crashes when player joins.

### ISSUE THREAD

**Issue by TurretCorruption** [polarathene/biglobby#19]
My game crashes whenever anyone joins my games. The people that join my games do in fact have the latest version of blt and the mod installed, yet whenever I invite them to my lobby, my game crashes. I think this could possibly be due to a Payday update that happened well before I downloaded the mod.

**Comment by polarathene** [comment]
If an update has come out since the last release of the mod, it likely needs to be patched again. I need the asset file network.network_settings, it is what pdmod file patches. As mentioned in previous issues it is a pain for me to do this with the frequent updates breaking the mod. I can only download at 100kb/s and have limited storage(almost always need 30GB free to install the update).

Provide that file and I'll have a go at patching for you.

**Comment by simon-wh** [comment]
Issue should be resolved in the latest version
