### ISSUE TITLE
Additionnal bots don't follow me in few missions

### ISSUE THREAD

**Issue by BadLucKWyvern** [polarathene/biglobby#39]
Hi again, its me D:

i don't know the exact name of these missions but.. the one with Locke and the cash bundle from the plane, only 3 bots are following me. all other bots stay in the sky

and the haloween prison with the giant cloacker, only 3 bots are following me after using the tyrolean to the floating wagon (trying to leave the nightmare)

for now, i only sew these 2 missions, maybe more can come... can you do something for this ?

**Comment by BadLucKWyvern** [comment]
Application has crashed: C++ exception
[string "lib/managers/group_ai_states/groupaistateba..."]:2828: attempt to index a nil value

can't do hoxton breakout day one and day 2 anymore... i lost my crime streak of 272 cause of the crash... Dx

**Comment by polarathene** [comment]
Hi, thanks for the report :) I'm not sure why that would be happening. Maybe Overkill messed with AI or event code breaking the changes I made or has new methods that need support. The crash info isn't too helpful, BLT has it's own log file, maybe if you're lucky it has some helpful info about something going wrong, give that a look next time you have a crash too.

No idea why hoxton breakout would break, has to be a change that Overkill did, sorry to hear about it ruining your streak :( Unfortunately as I've mentioned in other recent issues, I'm unable to commit time to further developing this mod for the time being due to demands of my career/life. I'm more than happy to mentor/advise another modder who'd like to help contribute a fix if you're able to find one, the reddit community has a payday modding subreddit that might be helpful.

**Comment by rockr230** [comment]
@BadLucKWyvern 
> Application has crashed: C++ exception
[string "lib/managers/group_ai_states/groupaistateba..."]:2828: attempt to index a nil value
can't do hoxton breakout day one and day 2 anymore...

I've seen this crash before, and in my experience, it occurs when a heister bot is duplicated. Did you make sure that you didn't set too many extra bots?
If you set the Lobby Size to 17 (Max possible Heisters) and Max Bot Size to 16 (Max possible extra bots while on single player), that works on most heists, EXCEPT Hoxton Breakout.
During Hoxton Breakout, if using the settings mentioned, and you're NOT playing as Hoxton, the game will crash. It might be that the "Hoxton" you help breakout is considered a heister bot. Oddly, when you do play as Hoxton during the heist, you don't crash (or rather, I didn't when I tried it).
EDIT: Just set the Lobby Size to 16 and Max Bot Size to 15, I'm sure missing one extra bot shouldn't be too bad.

> i lost my crime streak of 272 cause of the crash... Dx

Try this mod:
https://modworkshop.net/mydownloads.php?action=view_down&did=19568
Your crime spree won't reset if you crash in the middle of a crime spree heist.

**Comment by BadLucKWyvern** [comment]
THX a lot for your help. I completly forgot about duplicating hoxton... i
have to put the bot value to 15 and not 16
THX too for the anti streak ruinner mod. But i claimed my reward ;-;
I take it at least. Im sûre it will be usefull in the future

Polarathene, possible to add a bind that makes all bots teleporting at my
exact location ? Even bots witch arent following me anymore ?

**Comment by polarathene** [comment]
@BadLucKWyvern I do have a mod that allows for bringing players to you by putting them in custody and releasing. It could probably be modified for bots. I never released it(quite a lot of unreleased mods) and would have to dig it up sometime.

It's not really a feature suited for BigLobby, plus I don't see development resuming for a long time if ever right now. I don't mind updating the mod to the latest version of the game when it's causing crashes, but that's about all I have time for.

Glad the problem has been sorted as only a bot count/duplication issue :)

**Comment by BadLucKWyvern** [comment]
Ive lowered the bot nomber to 15 and keeped size to 17... still crashing D:

**Comment by polarathene** [comment]
Do you run into the issue on lower bot counts? It might be due to hoxton bot on the level like suggested? Try like 10 bots size 10 lobby. Bots will fill to the size set minus however many players like regular games do. If that still crashes, then try 5/5 and if that crashes try with 4/4. 

If 4/4 crashes then it's something wrong with the mod not the bots, probably UI but could be something else. If you don't get crashes with 4/4, can still be UI related 5-7 lobby size should confirm that. beyond 7/7 only and it's probably bot related.
