### ISSUE TITLE
Host crashes when client joins host

### ISSUE THREAD

**Issue by rockr230** [polarathene/biglobby#44]
Might be due to the recent updates to Payday 2.

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                        send()  lib/network/base/networkpeer.lua:1034               
                        send()  @mods/biglobby/lua/lib/network/base/_networkpeer.lua:14  
    on_join_request_received()  @mods/biglobby/lua/lib/network/base/session_states/_hoststateinlobby.lua:117  
    on_join_request_received()  lib/network/base/hostnetworksession.lua:55          
                                lib/network/base/handlers/connectionnetworkhandler.lua:50  

-------------------------------

**Comment by polarathene** [comment]
@rockr230 Yeah that looks like an update broke it. It's an easy fix usually, I've got a problem with some software I use to create the updates atm so there could be a delay. I'll notify you when a new release is made.

**Comment by lukespragg** [comment]
I noticed this last night as well, though I don't think there were any updates aside from nearly a week ago. It was only an issue with one player that had disabled Big Lobby via the Lua Mods menu to play in a regular game; it worked fine for those who didn't touch the mod. He did resolve it by re-uploading a patched bundle from me, though it's still a bit odd as we all played without issues the night before.

**Comment by Christley** [comment]
I've had this issue aswell. Worked this wednesday, but failed to work today (saturday).
What i did was reapply the mod until it started working. Took plenty of tries but then both me and the players could join eachother.
I love this mod so i hope this gets fixed. Sucks to leave 2-3 of your friends out because payday doesn't support more than 4 players

**Comment by polarathene** [comment]
I should have some time to work on it in the next 24 hours, fixed the software issue I was having.

**Comment by polarathene** [comment]
Update is ready, but turns out there is still a bug in my software I use(due to an OS update). So there will be a delay. These are the only changes:

```
<message name="kick_to_briefing" delivery="ordered" receiver="connection" check="server_to_client"/> 
 
<message name="set_waiting" delivery="ordered" receiver="connection" check="server_to_client"/> 
```
Not sure what `set_waiting` is for, as long as neither of those are triggered by anyone in the lobby(looks like both can only be actioned by host), then you shouldn't crash in the meantime.

**Comment by rockr230** [comment]
@polarathene the `"set_waiting"` might be in reference to the new drop-in prompt feature: http://www.overkillsoftware.com/the-henchmen-are-dropping-in-are-you-ready/

**Comment by polarathene** [comment]
Ah yep that's probably it, best to have that feature disabled then if possible as that'd cause a crash until I can push this update out.

**Comment by polarathene** [comment]
Sorry about the wait guys, you can find v2.43 [here](https://github.com/polarathene/biglobby/releases/tag/v2.43). Give it a try and let me know how it goes :) The new feature might cause some UI bugs if unlucky, hopefully not.

**Comment by rockr230** [comment]
Works! Thanks!

**Comment by Kazenin** [comment]
Does not work for me. Client Linux and Server Windows and Server Linux and Client Windows. Windows/Windows still crash.

**Comment by polarathene** [comment]
@Kazenin Is your crash report similar to the one shared here?

```
Current thread: Main
Script stack:
send() lib/network/base/networkpeer.lua:1034
send() /lua/lib/network/base/_networkpeer.lua:14
on_join_request_received() /lua/lib/network/base/session_states/_hoststateinlobby.lua:117
on_join_request_received() lib/network/base/hostnetworksession.lua:55
lib/network/base/handlers/connectionnetworkhandler.lua:50
```

If it is, make sure you're using the latest version(2.43) as linked above, both pdmod and blt mods enabled on both accounts. 

If you've not had BigLobby work for you in the past before it's quite possible you're doing something wrong on your end, if you have had it working in the past and it's breaking now but your crash report is different, then create a new issue sharing the report. Include any other helpful details like where the crash/problem happens if it's easy to reproduce and trigger, etc.

**Comment by Kazenin** [comment]
Thanks mate. It is working now. Excelent project. many many thanks. My friend was using an old version.
