### ISSUE TITLE
Host crashes when client joins

### ISSUE THREAD

**Issue by rockr230** [polarathene/biglobby#48]
Haven't had time to test with a friend until now.
Crash likely due to recent updates.

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                        send()  lib/network/base/networkpeer.lua:1034               
                        send()  @mods/biglobby/lua/lib/network/base/_networkpeer.lua:14  
    on_join_request_received()  @mods/biglobby/lua/lib/network/base/session_states/_hoststateinlobby.lua:117  
    on_join_request_received()  lib/network/base/hostnetworksession.lua:55          
                                lib/network/base/handlers/connectionnetworkhandler.lua:50  

-------------------------------

**Comment by polarathene** [comment]
It does look like a network method is causing the crash. I did a diff against `network.network_settings` from the update and I don't see any changes. I will need to know the function method it's trying to call, known as `func_name` [here](https://github.com/polarathene/biglobby/blob/master/biglobby/lua/lib/network/base/_networkpeer.lua).

I've not worked with the lua codebase in a while so not sure if this will work.

```Lua
BigLobbyGlobals:logger(func_name, false)
```

or

```Lua
log(func_name)
```

`func_name` should be a string, otherwise it needs to be `tostring(func_name)`, you can also try: 

```Lua
log("BL func_name: " .. func_name)
```

This should give you something to search for to find it better(ctrl+f), it should be in the BLT logs `/mods/logs/date_here.log` I think was the path.

**Comment by rockr230** [comment]
Newest update works!
