### ISSUE TITLE
Crash when trying to open the Sound settings for Custom Heist/Menu Track/Playlist

### ISSUE THREAD

**Issue by OtherACTION** [polarathene/biglobby#52]
Crash Log:

Application has crashed: C++ exception
...s/biglobby/lua/lib/managers/menu/_contractboxgui.lua:17: attempt to index a nil value

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                         ntdll  (???)     RtlInitUnicodeString                                

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.72.257
	CPU : Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : NVIDIA GeForce GT 750M / aticfx32.dll[6.14.10.8440]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8077MB 64KB
	OS : 6.1.7600 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Razer (Speakers (2- Razer Surround Audio Controller))

**Comment by karasuhebi** [comment]
How do you even get Big lobby? I don't see it on ModWorkshop and the one I have installed is not telling me I have an update. :-\

**Comment by OtherACTION** [comment]
@karasuhebi You have to download the latest release from here: https://github.com/polarathene/biglobby/releases/tag/v2.43

**Comment by karasuhebi** [comment]
I only see links to source code. :-\

**Comment by polarathene** [comment]
@karasuhebi Github calls it `Source Code` but the .zip is the mod release. Just download it and install, like first time. I have linked a video guide on the [main page](https://github.com/polarathene/biglobby) for the project if you have not installed before.

This mod does not support in game updating because it requires pdmod to update too.

**Comment by polarathene** [comment]
@OtherACTION The line it points to for the crash is [this one](https://github.com/polarathene/biglobby/blob/master/biglobby/lua/lib/managers/menu/_contractboxgui.lua#L17).

It doesn't make sense why that wouldn't work unless another mod has changed how many players should be there. It does not crash if just biglobby mod alone?

**Comment by karasuhebi** [comment]
Thanks @polarathene! Do you know why the mod doesn't auto-update?

**Comment by polarathene** [comment]
@karasuhebi I just said why, it has pdmod, it is not just BLT mod.

**Comment by OtherACTION** [comment]
@polarathene 
Just got done going through all the mods I had installed to try and find which mod was conflicting with biglobby. I have found 0 mods that would conflict and I have also removed all mods except for biglobby to see if there were multiple's that would cause this issue.

The issue continued after having biglobby being the only mod installed, so yes the game crashes when I try to enter the Custom Heist Track/Playlist & Custom Menu Track/Playlist when biglobby is the only mod running. And I agree that it doesn't make sense for the mod to crash the game when trying to enter a game menu which is under options > Sound.

**Comment by polarathene** [comment]
> Custom Heist Track/Playlist & Custom Menu Track/Playlist

Oh when you said Custom Heist I thought that was referring to BeardLib for custom levels. It's probably something to do with game update, if that sets the track for all players on the game and is a new feature most definitely the case. I'll see if it's an easy fix, otherwise it could be a problem :\

**Comment by polarathene** [comment]
@OtherACTION bad news, no new network methods. It requires going through the games codebase to figure out which I don't have time for these days. So unfortunately for the time being this is something you won't be able to do with biglobby :(

It might be possible to find someone who can help contribute a fix from the modding community but similar issues have shown no interest so far at getting help.

**Comment by karasuhebi** [comment]
@polarathene Thanks again!

**Comment by Shad0wlife** [comment]
This issue is caused by the session returned while calling
`local peer = managers.network:session():peer(i)`
being nil. I split that into
`local session = managers.network:session()
 local peer = session:peer(i)`
for testing and then already accessing the "session" variable returns an error trying to index something nil. It even says that that specific variable is nil (before it couldn't, there was no variable, only the returned value).

**Comment by Shad0wlife** [comment]
Ah, got it. The main funciton instantly quits if session is nil. But since you chain it one layer down, it wil only return to your code and thus still try to access session. Let me just clone the repo and do a pr real quick.

**Comment by polarathene** [comment]
There is a good chance that the developers changed the code and fixed that bug after the biglobby version was done. I rarely alter the game devs code in this mod, usually helpful comments indicate what was not changed, so anything different from that since would need to be updated. PR welcome :)
