### ISSUE TITLE
Keeps crashing my game when friends join my game

### ISSUE THREAD

**Issue by mrpepsi** [polarathene/biglobby#55]
When i join a game or make a contract and a friend joins me (or i join him) the game crashes.. I've tryied to find a solution to this but i couldnt find any, any help would be appreciated thanks.

**Comment by polarathene** [comment]
@mrpepsi Hi there! The game just updated and added some changes that my mod(pdmod file) need to add too. This is pretty common reason the mod crash. You can find new release [v2.44](https://github.com/polarathene/biglobby/releases/tag/v2.44) that should work fine. Give it a try and let me know :)

By the way make sure you both update BLT and PDMOD file just like install BigLobby first time, this mod does not auto-update because of PDMOD file.

**Comment by FeldwebelSchultz** [comment]
@polarathene Doesn't work for me. I have the same problems like mrpepsi.

I have the big lobby mod v2.44 und the latest version of BLT.

**Comment by polarathene** [comment]
Error logs please.

**Comment by polarathene** [comment]
Also, make sure you test with just biglobby mod enabled for both you and your friend joining. It could be another mod is causing problem with biglobby.

**Comment by FeldwebelSchultz** [comment]
After the least patch of Payday 2 i have tested it only with big lobby + BLT (latest update) and with them + WolfHUD.

Here are the logs.
[2017_07_08_log with WolfHUD.txt](https://github.com/polarathene/biglobby/files/1132516/2017_07_08_log.with.WolfHUD.txt)
[2017_07_08_log without WolfHUD.txt](https://github.com/polarathene/biglobby/files/1132517/2017_07_08_log.without.WolfHUD.txt)

**Comment by FVaeger** [comment]
paste your crashlog for your latest crash with the mod

**Comment by polarathene** [comment]
The game had an update not long after I made a release for the previous update. There were many changes made this time, give me a bit to make a new release. No point in crashlogs until then.

Overkill has increased the player cap from 4 to 15. They are planning to support more players like biglobby(though not as much) possibly for a special game mode or mutator. I need to look through game code to see how this affect biglobby. PDMod may no longer be required which would be good news, depending on game code, it may also be possible to only need host with mod to enable(without mutator or game mode only depending on what OVK have planned.

**Comment by polarathene** [comment]
@mrpepsi @FeldwebelSchultz Hi guys. An update came not long after I release 2.44. It had lots of changes this time, you can try [v2.45](https://github.com/polarathene/biglobby/releases/tag/v2.45-peer-change-to-15) and let me know if it's working again? Thanks :)

**Comment by FeldwebelSchultz** [comment]
@polarathene Yeah, it works fine. Thanks man! ;)

**Comment by mrpepsi** [comment]
Yeah mine works fine aswell only thing that doesnt work and makes my game crash is when i join a friend at a crime spree but i assume that doesnt work yet?

**Comment by polarathene** [comment]
@mrpepsi Your message about the crime spree issue seems to have disappeared, I read it in my e-mail notifications. I've not worked on the mod for a while, crime spree was introduced since then, I only update the network methods right now.

There is an issue [here](https://github.com/polarathene/biglobby/issues/37) that you can follow progress on, at the end a user mentions a workaround.
