### ISSUE TITLE
More than 18 bots in lobby?

### ISSUE THREAD

**Issue by mike546378** [polarathene/biglobby#59]
Hi, wondering if it is possible to have more than 18 bots in the lobby at a time? Options counter goes upto 128, however I crash at anything greater than 18 (presumably due to the fact that there are only 18 characters in the game )
Error code is as follows:

    Application has crashed: C++ exception
    [string "lib/managers/group_ai_states/groupaistateba..."]:2832: attempt to index a nil value
    
    
    
    SCRIPT STACK
    
    
    
    -------------------------------
    
    Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlGetCurrentDirectory_U                            
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 

    -------------------------------
    
    Current thread: Main
    
    -------------------------------
    
    System information:
    	Application version : 1.74.281.
	CPU : Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 970 / nvldumd.dll[22.21.13.8253]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16321MB 772KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headset (Strix 7.1))

Not sure if it will be possible, going to take a look through the code anyway and see if I can work something out though

**Comment by polarathene** [comment]
Hi, yes it is technically possible as far as I know. I was just unable to find the time to allocate to working on this feature. Lobby size can be greater than 128 by updating the pdmod and anywhere in lua if needed, I figured 128 would be high enough for most :)

The issue with exceeding the actual character limit is how the game handles duplicates. Overkill was a bit sloppy in some code(in fairness they didn't need to code with duplicates in mind). There is code that will look up and reference player data based on their character, this includes spawning each player with their player model I think.

The solution is to go through the codebase finding all these kinds of methods/usages to understand the scope, then ideally only modify code in a few places such as criminalmanager and character model lookup code. 

I haven't looked at the code in a while, but say the string for Clover was "clover"(which it's not, "female1" I think), you would instead have a counter or something so that the string is "clover_1" or a method that returns this modified string(a few do from memory) and all consumers of that method being able to use it without modification. If I recall correctly, the model lookup code would just truncate the suffix (eg "_1") and could lookup the specific character or model while keeping the suffix tied to the player/bot as a unique identifier.

It's a tedious feature to implement correctly, but shouldn't be a difficult one. The reason it currently crashes if not obvious, is because the player/bot that should be returned to the method call is the wrong one, but using the same character. It could be something like sending/releasing from custody and the code not being setup to handle it when the given player is in the wrong state.

**Comment by mike546378** [comment]
Thanks for the information, I figured the issue would be something similar to that. When I get a chance I'll take a look through the code and see if I can come up with a fix, will create a pull request if I make any progress

**Comment by polarathene** [comment]
@mike546378 That would be greatly appreciated :)

**Comment by polarathene** [comment]
I've been very busy working at a new startup company. Unfortunately I don't think I have the time to maintain this mod anymore for free. You can find a bounty link and more details in [this issue](https://github.com/polarathene/biglobby/issues/63) if you'd like to show some support to having the mod maintained.

I am closing this issue. This feature if you did not manage to have success with it, you could try create a seperate issue and bounty for at BountySource. I don't think I'd be able to find the time to do it personally but a paid bounty might help encourage someone else to complete the feature.
