### ISSUE TITLE
game crash when trying to load a singleplayer game

### ISSUE THREAD

**Issue by albert-softie** [polarathene/biglobby#60]
i haven't tried it online but i imagine it would have the same problem
i followed all the installation instructions as perfectly as i could
i have the better bots mod installed and enabled with the big lobby option enabled
i've tried with 20 and 14 bots enabled, and neither have seemed to have made a difference
i am playing on the most recent version of the game as of writing [update 152.1]
i even tried lowering my graphics settings as low as i could to see if it was a graphics issue, and it changed nothing
[here](https://pastebin.com/TQqzcyyR) is my most recent crashlog

**Comment by polarathene** [comment]
Hi @albert-softie , thanks for trying out the mod. As it's your first time it was probably bad timing due to the update. I will try to get an update of Biglobby pushed out in next few days, as long as it's just sync to the latest game update it should go smoothly, might need to add support for BLT 2.0 as well.

**Comment by polarathene** [comment]
Hi there sorry for the late response, I've been very busy working at a new startup company. Unfortunately I don't think I have the time to maintain this mod anymore for free. You can find a bounty link and more details in [this issue](https://github.com/polarathene/biglobby/issues/63) if you'd like to show some support to having the mod maintained.
